#!/usr/bin/env python

import doctest, unittest
from glob import glob

import tests.test_angles
import tests.test_bodies
import tests.test_dates
import tests.test_usno
import tests.usno_equinoxes

suite = unittest.TestSuite()
loader = unittest.defaultTestLoader
suite.addTest(loader.loadTestsFromModule(tests.test_angles))
suite.addTest(loader.loadTestsFromModule(tests.test_bodies))
suite.addTest(loader.loadTestsFromModule(tests.test_dates))
suite.addTest(loader.loadTestsFromModule(tests.test_usno))
suite.addTest(loader.loadTestsFromModule(tests.usno_equinoxes))

for path in glob('doc/*.rst'):
    suite.addTest(doctest.DocFileSuite(path))

runner = unittest.TextTestRunner()
runner.run(suite)
