#!/usr/bin/env python

import unittest

import tests.test_angles
import tests.test_bodies
import tests.test_dates
import tests.test_rst
import tests.test_usno
import tests.usno_equinoxes

suite = unittest.TestSuite()
loader = unittest.defaultTestLoader

suite.addTest(loader.loadTestsFromModule(tests.test_angles))
suite.addTest(loader.loadTestsFromModule(tests.test_bodies))
suite.addTest(loader.loadTestsFromModule(tests.test_dates))
suite.addTest(loader.loadTestsFromModule(tests.test_usno))
suite.addTest(loader.loadTestsFromModule(tests.usno_equinoxes))

for test in tests.test_rst.tests:
    suite.addTest(test)

runner = unittest.TextTestRunner()
runner.run(suite)
