#!/usr/bin/env python

import unittest

import tests.test_angles
import tests.test_bodies
import tests.test_dates

suite = unittest.TestSuite()
loader = unittest.defaultTestLoader
suite.addTest(loader.loadTestsFromModule(tests.test_angles))
suite.addTest(loader.loadTestsFromModule(tests.test_bodies))
suite.addTest(loader.loadTestsFromModule(tests.test_dates))
runner = unittest.TextTestRunner()
runner.run(suite)
